name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        credentials: ${{ secrets.GKE_CREDENTIALS }}
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Build frontend Docker image
      run: |
        cd demand-forecasting-app/frontend
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/schneider-frontend:v3 \
          --push .
    - name: Build backend Docker image
      run: |
        cd demand-forecasting-app/backend
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/schneider-backend:v1 \
          --push .
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Deploy to GKE
      run: |
        kubectl apply -f demand-forecasting-app/k8s/frontend-deployment.yaml
        kubectl apply -f demand-forecasting-app/k8s/backend-deployment.yaml
    - name: Check GKE deployment status
      run: kubectl get pods
